"""SPRINT 14, ENER-2 -- AT WHAT STRUCTURAL DISTANCE DOES DISCRIMINATION FAIL?

A global rank correlation hides the only thing a search cares about: the RESOLUTION of the
objective.  If an energy can tell a good structure from a 5 A decoy but not from a 1.5 A
decoy, then it is a garbage filter with an explicit resolution limit, and that single
threshold explains the entire architecture's behaviour.

Two independent formulations, both measured:

  (1) SEPARATION-CONDITIONED PAIRWISE ACCURACY (no anchor, no selection).
      Over pairs (i, j) whose mutual CA-RMSD lies in a bin around d, measure
          acc(d) = P( sign(E_i - E_j) == sign(RMSD_i^nat - RMSD_j^nat) ).
      0.5 is chance.  This is the objective's ability to order two structures that are d
      apart, which is exactly the decision a local search makes.

  (2) ANCHOR-VS-DECOY DISCRIMINATION (the classic decoy test).
      Anchors are good structures.  Decoys are generated by mutating m torsion states of
      the anchor, which sweeps the separation d.  Measure
          auc(d) = P( E_anchor < E_decoy ).
      NULL CONTROL: the identical construction around RANDOM anchors, where decoys at
      distance d are not systematically worse.  Any auc(d) > 0.5 in the null is the test
      measuring anchor-typicality rather than nativeness.

The anchor choice in (2) reads the true RMSD, so (2) is an ORACLE DIAGNOSTIC of resolution.
(1) reads the label only to score, exactly as every ranking metric in this project does.

The decoy sets are cached to `s14/cache/decoy_<PDB>.npz` and are importable by the other
workstreams:  `from s14 import ener_decoy as D; D.decoys("1CS9")`.

    python -m s14.ener_decoy [--amber]
"""
from __future__ import annotations

import os
import sys

import numpy as np

from s12 import instrument as I
from s14 import ener_lib as E

BINS = [(0.0, 0.75), (0.75, 1.25), (1.25, 1.75), (1.75, 2.5), (2.5, 3.5),
        (3.5, 4.5), (4.5, 6.0), (6.0, 99.0)]
BIN_LABEL = ["<0.75", "1.0", "1.5", "2.0", "3.0", "4.0", "5.0", ">6"]
GAP_BINS = [(0.0, 0.25), (0.25, 0.5), (0.5, 1.0), (1.0, 1.5), (1.5, 2.0),
            (2.0, 3.0), (3.0, 99.0)]
GAP_LABEL = ["<0.25", "0.5", "1.0", "1.5", "2.0", "3.0", ">3"]
N_ANCHOR = 8
N_PER_M = 60           # decoys per (anchor, mutation-count)
AMBER_STRIDE = 3       # AMBER is 28 ms/config: score every 3rd decoy (20 per cell)


# ------------------------------------------------------------------ (1) separation test
def separation_accuracy(pdb, n_pairs=400000, seed=0):
    """Pairwise decision accuracy as a function of the pair's mutual CA-RMSD.

    Uses the cached UNIFORM AMBER stratum so that AMBER is included at zero new cost and
    no objective sees a population the others do not.
    """
    z = E.enum(pdb)
    m = z.uniform_mask
    idx = z.amber_idx[m]
    R = z.rmsd[idx]
    ca = z.ca(idx)
    M = len(idx)
    rng = np.random.default_rng(seed)
    i = rng.integers(0, M, n_pairs); j = rng.integers(0, M, n_pairs)
    keep = i != j
    i, j = i[keep], j[keep]
    # mutual CA-RMSD for the sampled pairs, in chunks
    d = np.empty(len(i))
    CH = 20000
    for a in range(0, len(i), CH):
        A = ca[i[a:a + CH]]; Bv = ca[j[a:a + CH]]
        d[a:a + CH] = _rmsd_pairs(A, Bv)
    gap = np.abs(R[i] - R[j])
    objs = _objectives(z, idx, m)
    out, out_gap, out_2d = {}, {}, {}
    for name, v in objs.items():
        dE = v[i] - v[j]
        dR = R[i] - R[j]
        hit = (dE > 0) == (dR > 0)
        ok = dE != 0
        row = []
        for (lo, hi), lab in zip(BINS, BIN_LABEL):
            sel = (d >= lo) & (d < hi)
            row.append(_cell(sel, hit, ok, lab, gap))
        out[name] = row
        # the CONFOUND CONTROL: accuracy as a function of the true QUALITY GAP.
        # separation and gap are correlated, so an objective that only reads gap will
        # look like it has structural resolution.
        rowg = []
        for (lo, hi), lab in zip(GAP_BINS, GAP_LABEL):
            sel = (gap >= lo) & (gap < hi)
            rowg.append(_cell(sel, hit, ok, lab, gap))
        out_gap[name] = rowg
        # 2-D: separation x gap, to disentangle them
        grid = []
        for (glo, ghi), glab in zip(GAP_BINS, GAP_LABEL):
            r2 = []
            for (lo, hi), lab in zip(BINS, BIN_LABEL):
                sel = (gap >= glo) & (gap < ghi) & (d >= lo) & (d < hi)
                r2.append(_cell(sel, hit, ok, lab, gap))
            grid.append(dict(gap=glab, cells=r2))
        out_2d[name] = grid
    return dict(pdb=pdb, n_pool=int(M), bins=BIN_LABEL, gap_bins=GAP_LABEL,
                sep_hist=[int(((d >= lo) & (d < hi)).sum()) for lo, hi in BINS],
                gap_hist=[int(((gap >= lo) & (gap < hi)).sum()) for lo, hi in GAP_BINS],
                mean_gap_by_sep=[float(gap[(d >= lo) & (d < hi)].mean())
                                 if ((d >= lo) & (d < hi)).sum() else float("nan")
                                 for lo, hi in BINS],
                per_objective=out, per_objective_gap=out_gap, per_objective_2d=out_2d)


def _cell(sel, hit, ok, lab, gap):
    n = int(sel.sum())
    if n < 200:
        return dict(bin=lab, n=n, acc=float("nan"), tie_frac=float("nan"))
    s = sel & ok
    return dict(bin=lab, n=n,
                acc=float(hit[s].mean()) if s.sum() >= 50 else float("nan"),
                tie_frac=float(1.0 - ok[sel].mean()),
                mean_gap=float(gap[sel].mean()))


def _rmsd_pairs(A, B):
    """Element-wise CA-RMSD between two aligned batches (b,n,3)."""
    A = A - A.mean(1, keepdims=True); B = B - B.mean(1, keepdims=True)
    H = np.einsum("bni,bnj->bij", A, B)
    U, S, Vt = np.linalg.svd(H)
    dd = np.sign(np.linalg.det(np.einsum("bij,bjk->bik", Vt.transpose(0, 2, 1),
                                         U.transpose(0, 2, 1))))
    S = S.copy(); S[:, -1] *= dd
    num = (A ** 2).sum((1, 2)) + (B ** 2).sum((1, 2)) - 2.0 * S.sum(1)
    return np.sqrt(np.maximum(num, 0.0) / A.shape[1])


def _objectives(z, idx, amber_mask):
    o = {"legacy": z.legacy[idx], "prior": z.prior[idx],
         "amber": z.amber_total[amber_mask],
         "amber_soft": E.softcore(z.amber_total[amber_mask]),
         "legacy_nosteric": z.obj("legacy_nosteric")[idx]}
    for t in E.LEG_TERMS:
        o["leg_" + t] = z.leg[t][idx]
    for t in E.AMB_TERMS:
        o["amb_" + t] = z.amb[t][amber_mask]
    o["H_rank_leg+amb"] = E.rank_norm(o["legacy"]) + E.rank_norm(o["amber"])
    return o


# ------------------------------------------------------------------ (2) decoy generation
def build_decoys(pdb, seed=0, oracle_anchor=True):
    """Controlled decoys at known separation, by mutating m states of each anchor.

    Returns dict with `anchor_idx` (A,), `decoy_idx` (A, M, P), `sep` (A, M, P) the true
    mutual CA-RMSD, and `nmut` (M,).  Cached to `s14/cache/decoy_<PDB>[_null].npz`.
    """
    tag = "" if oracle_anchor else "_null"
    path = os.path.join(E.CACHE, f"decoy_{pdb}{tag}.npz")
    if os.path.exists(path):
        return {k: v for k, v in np.load(path).items()}
    z = E.enum(pdb)
    rng = np.random.default_rng(seed + (0 if oracle_anchor else 991))
    if oracle_anchor:
        # ORACLE: the good structures the test needs anchors to be
        cand = np.argsort(z.rmsd, kind="mergesort")[:200]
        anchors = rng.choice(cand, N_ANCHOR, replace=False)
    else:
        anchors = rng.choice(z.B, N_ANCHOR, replace=False)
    muts = np.arange(1, z.n + 1)
    A, M, P = len(anchors), len(muts), N_PER_M
    dec = np.empty((A, M, P), np.int64)
    S0 = z.states(anchors).astype(int)                     # (A, n)
    for a in range(A):
        for mi, m in enumerate(muts):
            S = np.repeat(S0[a][None], P, axis=0)
            for b in range(P):
                pos = rng.choice(z.n, m, replace=False)
                S[b, pos] = (S[b, pos] + rng.integers(1, z.k, m)) % z.k
            dec[a, mi] = z.index_of(S)
    # true mutual separation
    ca_a = z.ca(anchors)
    sep = np.empty((A, M, P))
    for a in range(A):
        flat = dec[a].reshape(-1)
        cb = z.ca(flat)
        sep[a] = I.kabsch_rmsd_batch(cb, ca_a[a]).reshape(M, P)
    out = dict(anchor_idx=anchors, decoy_idx=dec, sep=sep, nmut=muts,
               anchor_rmsd=z.rmsd[anchors], decoy_rmsd=z.rmsd[dec])
    np.savez_compressed(path, **out)
    return out


def decoys(pdb, oracle_anchor=True):
    return build_decoys(pdb, oracle_anchor=oracle_anchor)


# ------------------------------------------------------------------ (2) scoring
def decoy_auc(pdb, with_amber=False, oracle_anchor=True):
    """P(E_anchor < E_decoy) as a function of the anchor-decoy separation."""
    z = E.enum(pdb)
    D = decoys(pdb, oracle_anchor)
    anchors = D["anchor_idx"]; dec = D["decoy_idx"]; sep = D["sep"]
    flat = dec.reshape(-1)
    objs = {"legacy": (z.legacy[anchors], z.legacy[flat]),
            "prior": (z.prior[anchors], z.prior[flat]),
            "legacy_nosteric": (z.obj("legacy_nosteric")[anchors],
                                z.obj("legacy_nosteric")[flat])}
    for t in E.LEG_TERMS:
        objs["leg_" + t] = (z.leg[t][anchors], z.leg[t][flat])
    if with_amber:
        ea, ed = _amber_for(pdb, anchors, flat, oracle_anchor)
        objs["amber"] = (ea, ed)
    A, M, P = dec.shape
    out = {}
    for name, (ea, ed) in objs.items():
        ed = np.asarray(ed, float).reshape(A, M, P)
        ea = np.asarray(ea, float)
        row = []
        for (lo, hi), lab in zip(BINS, BIN_LABEL):
            num = den = tie = 0
            for a in range(A):
                s = (sep[a] >= lo) & (sep[a] < hi) & np.isfinite(ed[a])
                if not s.any():
                    continue
                dd = ed[a][s] - ea[a]
                num += int((dd > 0).sum()); tie += int((dd == 0).sum())
                den += int(s.sum())
            row.append(dict(bin=lab, n=den,
                            auc=float((num + 0.5 * tie) / den) if den >= 100
                            else float("nan"),
                            tie_frac=float(tie / den) if den else float("nan")))
        out[name] = row
    return dict(pdb=pdb, oracle_anchor=bool(oracle_anchor),
                anchor_rmsd_mean=float(D["anchor_rmsd"].mean()),
                per_objective=out,
                sep_by_nmut=[float(sep[:, m].mean()) for m in range(M)],
                drmsd_by_nmut=[float((D["decoy_rmsd"][:, m]
                                      - D["anchor_rmsd"][:, None]).mean())
                               for m in range(M)])


def _amber_for(pdb, anchors, flat, oracle_anchor):
    """Genuine AMBER single points on the decoy set.  28 ms each; cached."""
    tag = "" if oracle_anchor else "_null"
    path = os.path.join(E.CACHE, f"decoy_amber_{pdb}{tag}.npz")
    if os.path.exists(path):
        c = np.load(path)
        return c["anchor"], c["decoy"]
    z = E.enum(pdb)
    sp = z.space()
    E.wait_for_memory(1.5, f"amber-decoy-{pdb}")
    # AMBER costs 28 ms per DISTINCT configuration.  Score a deterministic stride of the
    # decoys (every AMBER_STRIDE-th within each (anchor, nmut) cell) plus every anchor.
    dec_flat = np.full(len(flat), np.nan)
    keep = np.zeros(len(flat), bool)
    keep[::AMBER_STRIDE] = True
    want = np.unique(np.concatenate([anchors, flat[keep]]))
    S = z.states(want)
    print(f"  {pdb}: AMBER on {len(want)} distinct configs "
          f"(~{len(want)*0.028:.0f} s)", flush=True)
    vals = np.asarray(Q_amber(sp, S), float)
    lut = dict(zip(want.tolist(), vals.tolist()))
    dec_flat[keep] = [lut[int(x)] for x in flat[keep]]
    anc = np.array([lut[int(x)] for x in anchors])
    np.savez_compressed(path, anchor=anc, decoy=dec_flat, uniq=want, uniq_energy=vals)
    return anc, dec_flat


def Q_amber(sp, S):
    from s13 import qarch_lib as Q
    return Q.amber_energies(sp, S, components=False, progress=1000)


# ------------------------------------------------------------------ main
def main(with_amber=False):
    sep_rows, auc_rows, null_rows = [], [], []
    for pdb in E.ENUM_TARGETS:
        sep_rows.append(separation_accuracy(pdb))
        auc_rows.append(decoy_auc(pdb, with_amber=with_amber, oracle_anchor=True))
        null_rows.append(decoy_auc(pdb, with_amber=with_amber, oracle_anchor=False))
        print(f"{pdb} done", flush=True)
    E.write("ener_decoy", dict(
        what="structural-resolution limit of every objective",
        bins=BIN_LABEL, with_amber=bool(with_amber),
        separation=sep_rows, decoy_auc=auc_rows, decoy_auc_null=null_rows),
        n_expected=len(E.ENUM_TARGETS))
    report(sep_rows, auc_rows, null_rows)
    return sep_rows, auc_rows, null_rows


def _agg(rows, field, key="per_objective", nbin=None):
    names = sorted(rows[0][key])
    nbin = nbin or len(rows[0][key][names[0]])
    out = {}
    for nm in names:
        vals = []
        for b in range(nbin):
            v = [r[key][nm][b][field] for r in rows]
            n = [r[key][nm][b]["n"] for r in rows]
            v = [x for x, c in zip(v, n) if c >= 100 and np.isfinite(x)]
            vals.append(float(np.mean(v)) if v else float("nan"))
        out[nm] = vals
    return out


def _cross(x, y, level):
    """Smallest gap at which accuracy first reaches `level`, linearly interpolated.

    Returns inf if the objective never reaches that accuracy on the measured range --
    which is itself the answer: the objective has no resolution at any quality gap.
    """
    x = np.asarray(x, float); y = np.asarray(y, float)
    for i in range(len(y)):
        if np.isfinite(y[i]) and y[i] >= level:
            if i == 0 or not np.isfinite(y[i - 1]):
                return float(x[i])
            f = (level - y[i - 1]) / (y[i] - y[i - 1]) if y[i] != y[i - 1] else 0.0
            return float(x[i - 1] + f * (x[i] - x[i - 1]))
    return float("inf")


def report(sep_rows, auc_rows, null_rows):
    print("\n=== (1) SEPARATION-CONDITIONED PAIRWISE ACCURACY (0.5 = chance) ===")
    print("pair mutual CA-RMSD bin ->")
    hdr = "  ".join(f"{b:>6s}" for b in BIN_LABEL)
    print(f"{'objective':22s} {hdr}")
    A = _agg(sep_rows, "acc")
    for nm in sorted(A):
        print(f"{nm:22s} " + "  ".join(f"{v:6.3f}" if np.isfinite(v) else "   nan"
                                       for v in A[nm]))
    print("\npair counts per bin (pooled): ",
          np.sum([r["sep_hist"] for r in sep_rows], axis=0).tolist())
    print("CONFOUND -- mean |RMSD gap| in each separation bin: ",
          [round(float(x), 3) for x in
           np.nanmean([r["mean_gap_by_sep"] for r in sep_rows], axis=0)])
    print("\n=== (1b) CONTROL: accuracy conditioned on the TRUE QUALITY GAP |dRMSD| ===")
    ghdr = "  ".join(f"{b:>6s}" for b in GAP_LABEL)
    print(f"{'objective':22s} {ghdr}")
    G = _agg(sep_rows, "acc", "per_objective_gap")
    for nm in sorted(G):
        print(f"{nm:22s} " + "  ".join(f"{v:6.3f}" if np.isfinite(v) else "   nan"
                                       for v in G[nm]))
    print("\n=== (1c) DISENTANGLED: accuracy at fixed gap, across separation ===")
    for nm in ("legacy", "amber", "leg_steric", "prior", "leg_torsion",
               "amb_nonbonded", "legacy_nosteric"):
        if nm not in sep_rows[0]["per_objective_2d"]:
            continue
        print(f"  -- {nm} --   rows = |dRMSD| gap, cols = separation")
        print(f"  {'gap':>6s} {hdr}")
        for gi, glab in enumerate(GAP_LABEL):
            cells = []
            for b in range(len(BIN_LABEL)):
                v = [r["per_objective_2d"][nm][gi]["cells"][b]["acc"] for r in sep_rows]
                n = [r["per_objective_2d"][nm][gi]["cells"][b]["n"] for r in sep_rows]
                v = [x for x, c in zip(v, n) if c >= 100 and np.isfinite(x)]
                cells.append(float(np.mean(v)) if v else float("nan"))
            print(f"  {glab:>6s} " + "  ".join(f"{v:6.3f}" if np.isfinite(v) else "   nan"
                                               for v in cells))
    print("\n=== (1d) RESOLUTION THRESHOLD: the |dRMSD| gap needed to reach an accuracy ===")
    print(f"{'objective':22s} {'gap@0.55':>10s} {'CI':>18s} {'gap@0.60':>10s} "
          f"{'acc@gap<0.25':>13s} {'acc@gap 0.5':>12s}")
    GC = [0.125, 0.375, 0.75, 1.25, 1.75, 2.5, 4.0]      # bin centres
    for nm in sorted(G):
        per = []
        for r in sep_rows:
            a = [c["acc"] for c in r["per_objective_gap"][nm]]
            n = [c["n"] for c in r["per_objective_gap"][nm]]
            a = [x if (c >= 100 and np.isfinite(x)) else np.nan for x, c in zip(a, n)]
            per.append(_cross(GC, a, 0.55))
        m, ci = E.bootstrap_mean_ci([x for x in per if np.isfinite(x)])
        t60 = _cross(GC, G[nm], 0.60)
        print(f"{nm:22s} {_cross(GC, G[nm], 0.55):10.2f} "
              f"[{ci[0]:6.2f},{ci[1]:6.2f}] {t60:10.2f} "
              f"{G[nm][0]:13.3f} {G[nm][1]:12.3f}")
    print("\n=== (2) ANCHOR-vs-DECOY AUC, ORACLE anchors (0.5 = chance) ===")
    print(f"{'objective':22s} {hdr}")
    B = _agg(auc_rows, "auc", "per_objective")
    C = _agg(null_rows, "auc", "per_objective")
    for nm in sorted(B):
        print(f"{nm:22s} " + "  ".join(f"{v:6.3f}" if np.isfinite(v) else "   nan"
                                       for v in B[nm]))
    print("\n=== (2-NULL) same construction, RANDOM anchors ===")
    print(f"{'objective':22s} {hdr}")
    for nm in sorted(C):
        print(f"{nm:22s} " + "  ".join(f"{v:6.3f}" if np.isfinite(v) else "   nan"
                                       for v in C[nm]))
    print("\n=== (2) ORACLE minus NULL -- the part that is about nativeness ===")
    print(f"{'objective':22s} {hdr}")
    for nm in sorted(B):
        print(f"{nm:22s} " + "  ".join(f"{b-c:+6.3f}" if np.isfinite(b) and np.isfinite(c)
                                       else "   nan" for b, c in zip(B[nm], C[nm])))


if __name__ == "__main__":
    main(with_amber="--amber" in sys.argv)
