"""s26/q_dla.py -- the DYNAMICAL LIE ALGEBRA of the deployed ansatz and of the ADAPT pools.

PROPERTY MEASUREMENT (A2, s26/PREREG_A2.md).  Reads no RMSD, no native.  It exists because
s25/QUANTUM.md section 7.1 says "NOT MEASURED: the dynamical Lie algebra actually generated by
{Y_q} and the CNOT-chain conjugations at fixed depth" (open item 4 of the state brief).

THE CONSTRUCTION
================
The deployed circuit is U = C R_L C R_{L-1} ... C R_1 on |0...0>, with R_l = prod_q RY(theta_{l,q})
= prod_q exp(-i theta_{l,q} Y_q / 2) and C the CNOT chain plus ring closure (a Clifford).  Moving
every C to the right,

    U = [C R_L C^-1] [C^2 R_{L-1} C^-2] ... [C^L R_1 C^-L] C^L,

so the parameter theta_{l,q} generates the Pauli string P_{l,q} = C^{L-l+1} Y_q C^{-(L-l+1)}
(a single string up to sign, because C is Clifford), and the trailing C^L is a fixed
permutation of the computational basis which changes no probability up to relabelling and
no Lie algebra at all.  Moving the C's to the LEFT instead gives the conjugate set
{C^{-k} Y_q C^{k} : k = 0..L-1}, related to this one by conjugation with C^L; the two
algebras are isomorphic and have the same dimension, and the test file checks it.

The dynamical Lie algebra (DLA) is the real Lie closure of {-i P_{l,q} / 2}.  The commutator
of two Pauli strings is zero if they commute and (up to a scalar) their product string if they
anticommute, so the closure can be computed EXACTLY on Pauli strings as a SET: represent a string
by bit vectors (x, z); two strings anticommute iff the symplectic product x.z' + z.x' is odd;
the product is (x ^ x', z ^ z').  Distinct strings are linearly independent, and the Lie algebra
generated by a set is spanned by right-normed nested commutators [g_1,[g_2,[...,g_k]]], each of
which is a scalar times a string reached by commuting generators into the current string; so
dim(DLA) = the size of the closure under "commute with a generator", found by breadth-first
search.  A cap (2^21 = 2,097,152 strings, the smallest power of two that holds so(2^11)) stops
the search on registers whose closure would not fit.

Every Y_q has one Y and CNOT conjugation preserves the parity of the Y count, so every P_{l,q}
has an ODD number of Y's; such strings are imaginary antisymmetric, -iP/2 is real antisymmetric,
and the odd-Y strings span exactly so(2^n): their number is (4^n - 2^n)/2 = 2^(n-1)(2^n - 1) =
dim so(2^n).  The closure is checked to stay inside that set.

CROSS-CHECK
===========
At n = 4 and 5 the same closure is computed numerically: nested commutators of dense matrices
-iP/2, rank by SVD with a relative tolerance of 1e-10, iterated to convergence.  The two routes
must agree exactly on the dimension.

THE ADAPT SETS
==============
For each ADAPT pool (V, G, L2 of s26/q_adapt.py) the closure of the WHOLE pool is reported, and
for the operator sequences ADAPT selects on the deployed energy shape (standardised ranks
1..2^n, the two VQE_LFO cells) the closure of the selected strings (initial RY layer included)
at every growth step.

Artefact: s26/results/q_dla.json (s24.stats_lib.save_atomic, resumable per n).
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys
import time

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)
for _v in ("OMP_NUM_THREADS", "MKL_NUM_THREADS", "OPENBLAS_NUM_THREADS"):
    os.environ.setdefault(_v, "1")

from s26.q_adapt import (Pauli, make_pool, popcount, ry_layer_ops, run_adapt,   # noqa: E402
                         POOLS)

RESULTS = os.path.join(HERE, "results")
os.makedirs(RESULTS, exist_ok=True)
CAP = 1 << 21          # 2,097,152 >= dim so(2^11) = 2,096,128


def dim_so(n):
    return (1 << (n - 1)) * ((1 << n) - 1)


def dim_su(n):
    return 4 ** n - 1


# ============================================================ Clifford conjugation
def conj_cnot(P: Pauli, c: int, t: int) -> Pauli:
    """CNOT(c,t) P CNOT(c,t), phase dropped: X_c -> X_c X_t, Z_t -> Z_c Z_t."""
    n = P.n
    bc, bt = 1 << (n - 1 - c), 1 << (n - 1 - t)
    x, z = P.x, P.z
    if x & bc:
        x ^= bt
    if z & bt:
        z ^= bc
    return Pauli(n, x, z)


def entangler_pairs(n, ring=True):
    pairs = [(q, q + 1) for q in range(n - 1)]
    if ring and n > 2:
        pairs.append((n - 1, 0))
    return pairs


def conj_entangler(P: Pauli, ring=True, power=1) -> Pauli:
    """C^power P C^-power with C = CNOT(n-1,0) ... CNOT(0,1) (CNOT(0,1) applied first).

    C P C^-1 = c_m(... c_1(P) ...): the single-gate maps are applied in gate order.
    """
    for _ in range(int(power)):
        for c, t in entangler_pairs(P.n, ring):
            P = conj_cnot(P, c, t)
    return P


def fixed_generators(n, L, ring=True, convention="right"):
    """The effective Pauli generators of the deployed ansatz at depth L.

    right: {C^k Y_q C^-k : k = 1..L}     (C's moved to the right, the docstring's form)
    left : {C^-k Y_q C^k : k = 0..L-1}   (C's moved to the left; conjugate set)
    """
    gens = []
    for q in range(n):
        Y = ry_layer_ops(n)[q]
        for k in range(1, L + 1) if convention == "right" else range(0, L):
            if convention == "right":
                gens.append(conj_entangler(Y, ring, power=k))
            else:
                gens.append(conj_entangler_inverse(Y, ring, power=k))
    return gens


def conj_entangler_inverse(P: Pauli, ring=True, power=1) -> Pauli:
    """C^-power P C^power: the gates in REVERSE order (each CNOT is its own inverse)."""
    for _ in range(int(power)):
        for c, t in reversed(entangler_pairs(P.n, ring)):
            P = conj_cnot(P, c, t)
    return P


# ============================================================ symbolic closure
def lie_closure(gens, cap=CAP, max_rounds=10_000):
    """Exact Lie closure of a set of Pauli strings, as a set, by breadth-first search.

    Returns dict(dim, exceeded_cap, rounds, all_odd_y, n_gens_distinct, weight_hist).
    """
    if not gens:
        return dict(dim=0, exceeded_cap=False, rounds=0, all_odd_y=True, n_gens_distinct=0)
    n = gens[0].n
    if n > 12:
        raise ValueError("lie_closure: n > 12 needs 4^n membership bits; not attempted")
    gx = np.array([g.x for g in gens], np.uint64)
    gz = np.array([g.z for g in gens], np.uint64)
    shift = np.uint64(n)
    #: membership as one bool per (x, z) pair: 4^n bits, 16 MB at n = 12
    seen = np.zeros(1 << (2 * n), bool)
    count = 0
    fx, fz = [], []
    for g in gens:
        k = g.key()
        if not seen[k]:
            seen[k] = True
            count += 1
            fx.append(g.x)
            fz.append(g.z)
    n_gens = count
    Fx = np.array(fx, np.uint64)
    Fz = np.array(fz, np.uint64)
    rounds = 0
    exceeded = False
    while len(Fx) and rounds < max_rounds:
        rounds += 1
        nx_all, nz_all = [], []
        for a, b in zip(gx, gz):
            anti = ((popcount(Fx & b) + popcount(Fz & a)) & 1) == 1
            if not anti.any():
                continue
            nx = Fx[anti] ^ a
            nz = Fz[anti] ^ b
            keys = ((nx << shift) | nz).astype(np.int64)
            keys, idx = np.unique(keys, return_index=True)
            fresh = ~seen[keys]
            if fresh.any():
                kk = keys[fresh]
                seen[kk] = True
                count += int(len(kk))
                nx_all.append(nx[idx][fresh])
                nz_all.append(nz[idx][fresh])
                if count > cap:
                    exceeded = True
                    break
        if exceeded:
            break
        if nx_all:
            Fx = np.concatenate(nx_all)
            Fz = np.concatenate(nz_all)
            # de-duplicate the frontier (a string may be reached from two generators)
            keys = (Fx << shift) | Fz
            _, idx = np.unique(keys, return_index=True)
            Fx, Fz = Fx[idx], Fz[idx]
        else:
            Fx = np.array([], np.uint64)
            Fz = np.array([], np.uint64)
    if exceeded:
        return dict(dim=int(count), exceeded_cap=True, rounds=int(rounds), all_odd_y=None,
                    n_gens_distinct=int(n_gens), weight_hist=None)
    keys = np.flatnonzero(seen).astype(np.uint64)
    mask = np.uint64((1 << n) - 1)
    X = keys >> shift
    Z = keys & mask
    ny = popcount(X & Z)
    w = popcount(X | Z)
    assert int(len(keys)) == count
    return dict(dim=int(count), exceeded_cap=False, rounds=int(rounds),
                all_odd_y=bool(((ny & 1) == 1).all()),
                n_gens_distinct=int(n_gens),
                weight_hist=np.bincount(w, minlength=n + 1).tolist())


# ============================================================ numeric closure
_I = np.eye(2)
_X = np.array([[0, 1], [1, 0]], complex)
_Y = np.array([[0, -1j], [1j, 0]], complex)
_Z = np.array([[1, 0], [0, -1]], complex)


def dense_pauli(P: Pauli):
    M = np.eye(1, dtype=complex)
    for ch in P.word():
        M = np.kron(M, {"I": _I, "X": _X, "Y": _Y, "Z": _Z}[ch])
    return M


def numeric_closure(gens, rtol=1e-10, max_rounds=200):
    """dim of the real Lie algebra generated by {-iP/2}: nested dense commutators, SVD rank."""
    n = gens[0].n
    dim = 1 << n
    A = [(-1j) * dense_pauli(g) / 2.0 for g in gens]
    if all(np.abs(a.imag).max() < 1e-14 for a in A):
        A = [a.real for a in A]

    def rank_of(vs):
        M = np.stack([v.ravel() for v in vs])
        s = np.linalg.svd(M, compute_uv=False)
        return int((s > rtol * s[0]).sum()) if s.size else 0

    def basis_of(vs):
        M = np.stack([v.ravel() for v in vs])
        U, s, Vt = np.linalg.svd(M, full_matrices=False)
        keep = s > rtol * s[0]
        return [Vt[i].reshape(dim, dim) for i in range(len(s)) if keep[i]]

    basis = basis_of(A)
    new = list(basis)
    rounds = 0
    while rounds < max_rounds:
        rounds += 1
        comms = [g @ b - b @ g for g in A for b in new]
        cand = basis + comms
        r_old = len(basis)
        basis = basis_of(cand)
        if len(basis) == r_old:
            break
        # the new directions are those orthogonal to the old span; SVD basis mixes them,
        # so commute the whole basis next round (cheap at n <= 5)
        new = basis
    return dict(dim=int(len(basis)), rounds=rounds, real=bool(np.isrealobj(A[0])))


# ============================================================ the sweeps
def deployed_E(dim):
    r = np.arange(1, dim + 1, dtype=float)
    return (r - r.mean()) / r.std()


def sweep_fixed(ns, depths, ring=True, out=None):
    out = {} if out is None else out
    for n in ns:
        for L in depths:
            key = f"n{n}_L{L}"
            if key in out:
                continue
            t0 = time.perf_counter()
            gens = fixed_generators(n, L, ring=ring, convention="right")
            r = lie_closure(gens)
            r.update(n=n, L=L, P=n * L, dim_so=dim_so(n), dim_su=dim_su(n),
                     frac_of_so=(r["dim"] / dim_so(n)) if not r["exceeded_cap"] else None,
                     generators=[g.word() for g in gens], wall=round(time.perf_counter() - t0, 2))
            out[key] = r
            print(f"  fixed n={n:2d} L={L:2d} P={n * L:3d}  dim(DLA) = "
                  f"{'>' + str(CAP) if r['exceeded_cap'] else r['dim']:>9}   so(2^n) = {dim_so(n):>9}"
                  f"   su(2^n) = {dim_su(n):>9}   odd-Y {r['all_odd_y']}  ({r['wall']} s)", flush=True)
            if r["exceeded_cap"]:
                break
    return out


def sweep_pools(ns, pools=("V", "G", "L2"), out=None):
    out = {} if out is None else out
    for n in ns:
        for pn in pools:
            key = f"{pn}_n{n}"
            if key in out:
                continue
            gens = make_pool(pn, n)
            r = lie_closure(gens)
            r.update(n=n, pool=pn, pool_size=len(gens), dim_so=dim_so(n), dim_su=dim_su(n),
                     frac_of_so=(r["dim"] / dim_so(n)) if not r["exceeded_cap"] else None)
            out[key] = r
            print(f"  pool {pn:3s} n={n:2d} size={len(gens):3d}  dim(DLA) = "
                  f"{'>' + str(CAP) if r['exceeded_cap'] else r['dim']:>9}   so(2^n) = {dim_so(n):>9}",
                  flush=True)
    return out


def sweep_adapt_sets(n, cells, pools=("V", "L2"), adam_steps=50, seed=0, out=None,
                     optimisers=("adam_best", "lbfgs")):
    """The closure of ADAPT's selected strings at every growth step, deployed E shape."""
    out = {} if out is None else out
    E = deployed_E(1 << n)
    for pn in pools:
        for opt in optimisers:
            for alpha, T in cells:
                key = f"adapt_{pn}_{opt}_n{n}_a{alpha}_T{T}"
                if key in out:
                    continue
                r = run_adapt(E, alpha, T, n, pn, max_params=3 * n, adam_steps=adam_steps,
                              seed=seed, optimiser=opt)
                ops = [Pauli.from_word(w) for w in r["ops"]]
                ladder = []
                for k in range(n, len(ops) + 1):
                    c = lie_closure(ops[:k])
                    ladder.append(dict(P=k, dim=c["dim"], exceeded=c["exceeded_cap"],
                                       last_op=ops[k - 1].word()))
                out[key] = dict(n=n, pool=pn, optimiser=opt, alpha=alpha, T=T,
                                sequence=r["sequence"], stopped=r["stopped"],
                                n_distinct_ops=r["n_distinct_ops"],
                                consecutive_repeats=r["consecutive_repeats"],
                                F_final=r["final"]["F"], ladder=ladder, dim_so=dim_so(n))
                print(f"  ADAPT {pn} {opt} n={n} a={alpha} T={T} stop={r['stopped']}: "
                      f"seq {r['sequence']}\n     dim(DLA) by P: "
                      f"{[(x['P'], x['dim']) for x in ladder]}   so = {dim_so(n)}", flush=True)
    return out


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--ns", default="4,5,6,7,8,9,10,11")
    ap.add_argument("--depths", default="1,2,3,4,5,6")
    ap.add_argument("--adapt-n", type=int, default=7)
    ap.add_argument("--adapt-cells", default="1.0:0.3,0.25:0.3")
    ap.add_argument("--numeric-ns", default="4,5")
    ap.add_argument("--out", default=os.path.join(RESULTS, "q_dla.json"))
    a = ap.parse_args(argv)
    from s24 import stats_lib as ST
    R = {}
    if os.path.exists(a.out):
        try:
            with open(a.out) as fh:
                R = json.load(fh).get("results", {})
        except Exception:                                                # noqa: BLE001
            R = {}
    ns = [int(x) for x in a.ns.split(",")]
    depths = [int(x) for x in a.depths.split(",")]

    def save():
        ST.save_atomic(a.out, dict(kind="property measurement, dynamical Lie algebra, no RMSD",
                                   lane="Q", sprint=26, prereg="s26/PREREG_A2.md", cap=CAP,
                                   results=R), module_file=__file__)

    print("1. THE FIXED ANSATZ: dim(DLA) by width and depth (symbolic, exact)")
    R["fixed"] = sweep_fixed(ns, depths, out=R.get("fixed", {}))
    save()

    print("\n2. NUMERIC CROSS-CHECK at small n (dense commutators, SVD rank, rtol 1e-10)")
    R.setdefault("numeric", {})
    for n in [int(x) for x in a.numeric_ns.split(",")]:
        for L in depths:
            key = f"n{n}_L{L}"
            if key in R["numeric"]:
                continue
            gens = fixed_generators(n, L)
            r = numeric_closure(gens)
            sym = R["fixed"].get(key, {}).get("dim")
            r.update(n=n, L=L, symbolic_dim=sym, agree=(sym == r["dim"]))
            R["numeric"][key] = r
            print(f"  n={n} L={L}: numeric dim {r['dim']}  symbolic {sym}  agree {r['agree']}", flush=True)
        # both conventions
        for L in depths:
            key = f"left_n{n}_L{L}"
            if key in R["numeric"]:
                continue
            gl = fixed_generators(n, L, convention="left")
            R["numeric"][key] = dict(n=n, L=L, dim_left=lie_closure(gl)["dim"],
                                     dim_right=R["fixed"][f"n{n}_L{L}"]["dim"])
    save()

    print("\n3. THE ADAPT POOLS: closure of the whole pool")
    R["pools"] = sweep_pools([x for x in ns if x <= 9], out=R.get("pools", {}))
    save()

    print("\n4. ADAPT-SELECTED SETS on the deployed energy shape, closure at every growth step")
    cells = [tuple(float(y) for y in x.split(":")) for x in a.adapt_cells.split(",")]
    R["adapt_sets"] = sweep_adapt_sets(a.adapt_n, cells, out=R.get("adapt_sets", {}))
    save()
    print("\nwrote", a.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
