"""s25/resultslab/site.py -- render the static browse site into `results/site/`.

SELF-CONTAINED STATIC BUILD, NO SERVER.  `results/site/index.html` opens straight off the
filesystem.  That constraint decides one design point: structure files are NOT fetched at
runtime.  A `file://` page cannot `fetch()` a sibling file (CORS), so the generator inlines
every exported PDB into `structures.js` as `window.STRUCTURES[stem] = "<pdb text>"`, which a
plain `<script src>` loads from disk without a server.  The canonical `.pdb` files still
exist on disk in `results/structures/` -- the site is a second copy, never the only one.

The one external dependency is 3Dmol.js from cdnjs at a PINNED exact version.  If it cannot
be reached the panes say so and every number on the page is unaffected, because all of them
were computed offline by `schema.py`.
"""
from __future__ import annotations

import datetime
import json
import os
import shutil
import sys
from typing import Dict, List, Optional, Sequence

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from s24 import stats_lib as ST                     # noqa: E402
from s25.resultslab import exportlib as EX          # noqa: E402

TEMPLATE = os.path.join(HERE, "site")
ASSETS = ("index.html", "style.css", "app.js")

#: Purely descriptive; `build.py` overrides it with whatever the frozen architecture is.
DEFAULT_ARCHITECTURE = {
    "pipeline": "sequence -> prior/representation -> candidates -> Hamiltonian evaluation "
                "-> CVaR-VQE selection -> CVaR tail -> ensemble -> structure",
    "endpoint": "mean full-chain Ca-RMSD, 126 cluster-disjoint dev targets, BUILT-CHAIN basis",
    "basis ruling": "s25 L4/L8: the built chain is the production result; the point cloud is "
                    "retained as an explicitly labelled non-physical intermediate and the "
                    "two are always reported paired",
    "release gate": "no configuration may score below the ORACLE best member of its own "
                    "K=500 candidate pool (mean 1.7108 A)",
    "status": "NOT FROZEN -- this page is infrastructure proof, not a final result",
}


def _js_string(s: str) -> str:
    return json.dumps(s)


def render(payload: Dict[str, object], out_dir: str = EX.SITE_DIR,
           architecture: Optional[Dict[str, object]] = None,
           verbose: bool = True) -> str:
    os.makedirs(out_dir, exist_ok=True)
    for a in ASSETS:
        shutil.copyfile(os.path.join(TEMPLATE, a), os.path.join(out_dir, a))

    prov = ST.provenance(os.path.join(HERE, "site.py"))
    meta = {
        "basis": payload["basis"], "basis_note": payload["basis_note"],
        "basis_secondary": payload["basis_secondary"],
        "basis_secondary_note": payload["basis_secondary_note"],
        "chain_lam": payload["chain_lam"],
        "pool_gate_rule": payload["pool_gate_rule"],
        "difficulty_gate_rule": payload["difficulty_gate_rule"],
        "baseline": payload["baseline"], "configurations": payload["configurations"],
        "n_targets": payload["n_targets"], "status": payload["status"],
        "contains_synthetic": payload["contains_synthetic"],
        "label": payload["label"],
        "target_map_digest": payload["target_map_digest"],
        "mde_rule": payload["mde_rule"],
        "git_commit": prov.get("git_commit"),
        "module_hash": payload["records"][0]["module_hash"] if payload["records"] else None,
        "generated": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
        "architecture": dict(architecture or DEFAULT_ARCHITECTURE),
        "viewer_library": "3Dmol.js 2.5.5 (cdnjs, pinned)",
    }
    targets = [{k: t[k] for k in ("target_id", "pdb_id", "sequence", "length", "fold")}
               for t in EX.target_rows()]
    seen = {r["target_id"] for r in payload["records"]}
    targets = [t for t in targets if t["target_id"] in seen]

    data = {"meta": meta, "targets": targets, "leaderboard": payload["leaderboard"],
            "records": payload["records"]}
    dp = os.path.join(out_dir, "data.js")
    tmp = dp + ".tmp"
    with open(tmp, "w", newline="\n") as fh:
        fh.write("/* generated by s25/resultslab/site.py -- do not edit */\n")
        fh.write("window.RESULTS_DATA = ")
        json.dump(data, fh)
        fh.write(";\n")
    os.replace(tmp, dp)

    # Inline every structure this payload references, on BOTH bases, plus the shared native.
    # Keys are "<T-number>__<configuration>__<basis>".  The basis is part of the key so the
    # viewer physically cannot load a structure on one basis while printing the RMSD of the
    # other -- the failure that produced the L4 ruling.
    wanted = []
    for r in payload["records"]:
        # from the RECORD, not recomputed: a sandboxed selftest keeps its natives out of
        # results/ too, and the record is the only thing that knows where they went
        if r["native_path"]:
            wanted.append((EX.stem(r["target_id"], EX.NATIVE), EX.BASIS_NATIVE,
                           os.path.join(ROOT, r["native_path"])))
        if r["prediction_path"]:
            wanted.append((EX.stem(r["target_id"], r["configuration"]), r["basis"],
                           os.path.join(ROOT, r["prediction_path"])))
        if r.get("prediction_path_secondary"):
            wanted.append((EX.stem(r["target_id"], r["configuration"]), r["basis_secondary"],
                           os.path.join(ROOT, r["prediction_path_secondary"])))
    seen_keys, entries = set(), []
    for stem_, basis, path in wanted:
        key = "%s__%s" % (stem_, basis)
        if key in seen_keys or not os.path.exists(path):
            continue
        seen_keys.add(key)
        entries.append((key, path))
    entries.sort()

    sp = os.path.join(out_dir, "structures.js")
    tmp = sp + ".tmp"
    n_bytes = 0
    with open(tmp, "w", newline="\n") as fh:
        fh.write("/* generated by s25/resultslab/site.py -- inlined so the page works from file:// */\n")
        fh.write("window.STRUCTURES = {\n")
        for k, (key, path) in enumerate(entries):
            with open(path) as g:
                txt = g.read()
            n_bytes += len(txt)
            fh.write("%s: %s%s\n" % (_js_string(key), _js_string(txt),
                                     "," if k < len(entries) - 1 else ""))
        fh.write("};\n")
    os.replace(tmp, sp)

    if verbose:
        print("  site -> %s  (%d structures inlined, %.1f MB of coordinates)"
              % (os.path.relpath(out_dir, ROOT), len(entries), n_bytes / 1e6))
        print("  open: %s" % os.path.join(out_dir, "index.html"))
    return out_dir
